name: Update rules status

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update_and_commit:
    name: Update and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: log
        run: |
          echo "testing"        
          git remote -v
      - name: Commit changes
        run: |
          echo $(openssl rand -hex 12) > foo.txt
          git add foo.txt
          git config --local user.name 'Elastic Machine'
          git config --local user.email 'elasticmachine@users.noreply.github.com'
          git commit -m "Update rules markdown files"
          echo "pr is ${{ github.event.number }}"
          echo "base ref is ${{ github.base_ref }}"
          echo "head ref is ${{ github.head_ref }}"
          echo "ref is ${{ github.ref }}"
          git push origin refs/pull/${{ github.event.number }}/head:HEAD