name: Update rules status

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update_and_commit:
    name: Update and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          token: ${{secrets.ci-test-token}}
        
      - name: log
        run: |
          echo "testing"        
          git remote -v
      - name: Commit changes
        run: |
          echo $(openssl rand -hex 12) > foo.txt
          git add foo.txt
          git config --local user.name 'Elastic Machine'
          git config --local user.email 'elasticmachine@users.noreply.github.com'
          git commit -m "Update rules markdown files"
          git remote add fork git@github.com:orouz/ci_tests.git
          git remote -v
          echo "pr is ${{ github.event.number }}
          git push fork HEAD:${{github.head_ref}}